// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chat struct {
	UserID  string `json:"user_id"`
	Message string `json:"message"`
}

type NewMessage struct {
	Message string `json:"message"`
	UserID  string `json:"user_id"`
}

type Service struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Schema  string `json:"schema"`
}
